In [2]:
import pandas as pd
ads = pd.read_csv("Advertising.csv", usecols=[1,2,3,4])
df = ads.copy()
df.head(10)

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9
5    8.7   48.9       75.0    7.2
6   57.5   32.8       23.5   11.8
7  120.2   19.6       11.6   13.2
8    8.6    2.1        1.0    4.8
9  199.8    2.6       21.2   10.6

In [7]:
X = df.drop("sales", axis=1)
X[0:10]

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4
5    8.7   48.9       75.0
6   57.5   32.8       23.5
7  120.2   19.6       11.6
8    8.6    2.1        1.0
9  199.8    2.6       21.2

In [8]:
y = df["sales"]
y[0:5]

0    22.1
1    10.4
2     9.3
3    18.5
4    12.9
Name: sales, dtype: float64

In [9]:
from sklearn.model_selection import train_test_split, cross_val_score, cross_val_predict

X_train, X_test, y_Train, y_Test = train_test_split(X, y, test_size=0.2, random_state=42)

In [10]:
X_train.shape

(160, 3)

In [12]:
y_Train.shape

(160,)

In [13]:
X_test.shape

(40, 3)

In [14]:
y_Test.shape

(40,)

In [15]:
training = df.copy()

<hr>
<b>STATSMODELS</b>

In [18]:
import statsmodels.api as sm

lm = sm.OLS(y_Train, X_train)
model = lm.fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                  sales   R-squared (uncentered):                   0.982
Model:                            OLS   Adj. R-squared (uncentered):              0.982
Method:                 Least Squares   F-statistic:                              2935.
Date:                Wed, 02 Apr 2025   Prob (F-statistic):                   1.28e-137
Time:                        02:59:37   Log-Likelihood:                         -336.65
No. Observations:                 160   AIC:                                      679.3
Df Residuals:                     157   BIC:                                      688.5
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
TV             0.0531      0.001     36.467      0.000       0.050       0.056
radio          0.2188      0.011     20.138      0.000       0.197       0.240
newspaper      0.0239      0.008      3.011      0.003       0.008       0.040
==============================================================================
Omnibus:                       11.405   Durbin-Watson:                   1.895
Prob(Omnibus):                  0.003   Jarque-Bera (JB):               15.574
Skew:                          -0.432   Prob(JB):                     0.000415
Kurtosis:                       4.261   Cond. No.                         13.5
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [20]:
model.summary().tables[1]

<class 'statsmodels.iolib.table.SimpleTable'>

<hr>
<b>Scikit Learn</b>

In [23]:
from sklearn.linear_model import LinearRegression

lm = LinearRegression()
model = lm.fit(X_train, y_Train)
model.intercept_

2.979067338122629

In [24]:
model.coef_

array([0.04472952, 0.18919505, 0.00276111])

In [26]:
#math equation

#sales = 2.98 + 0.04*TV + radio*0.19 + newspaper*0.003
# 30 TV, 10 radio, 40 newspaper spendings. how much must sales be?

new_data = [[30],[10],[40]]
new_data = pd.DataFrame(new_data).T 

In [27]:
model.predict(new_data)

c:\Users\Lenovo\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([6.32334798])

In [28]:
import numpy as np
from sklearn.metrics import mean_squared_error

y_pred = model.predict(X_train)
rmse = np.sqrt(mean_squared_error(y_Train, y_pred))

In [29]:
rmse

1.644727765644337

In [30]:

y_pred_test = model.predict(X_test)
rmse_test = np.sqrt(mean_squared_error(y_Test, y_pred_test))
rmse_test

1.7815996615334502

<b>Model Tuning</b>

In [32]:
model.score(X_train, y_Train)

0.8957008271017818

In [37]:
cross_val_score(model, X_train, y_Train, cv=10, scoring="r2")

array([-0.10975169,  0.87992761,  0.88460907,  0.95616404,  0.93017934,
        0.92369938,  0.86467693,  0.95081368,  0.7622523 ,  0.87097792])

In [38]:
cross_val_score(model, X_train, y_Train, cv=10, scoring="r2").mean()

0.791354859691634

In [45]:
cross_val_score(model, X_test, y_Test, cv=10, scoring="r2").mean()

0.7007204329162284

In [42]:
np.sqrt(-cross_val_score(model, 
                X_train, 
                y_Train, 
                cv=10, 
                scoring="neg_mean_squared_error")).mean()

1.6513523730313335

In [46]:
np.sqrt(-cross_val_score(model, 
                X_test, 
                y_Test, 
                cv=10, 
                scoring="neg_mean_squared_error")).mean()

1.8462778823997095